### ISSUE TITLE
ページのカラーテーマを決定するコンフィグを追加・複数のカラーテーマを先方に共有できるように

### ISSUE THREAD

**Issue by machimachida** [KentaroUchida/SandaBousaiNote#18]
createThemeみたいなmaterial-uiの設定で確か作れます。
複数のカラーテーマの共有方法については、「別ページを作る」もしくは「複数のデプロイ環境を作る」のどちらかの方法で行ってください。

**Comment by alttkymmm** [comment]
要は、色を変える
