### ISSUE TITLE
三田版のレビュー_P4ゆれがおさまったら

### ISSUE THREAD

**Issue by alttkymmm** [KentaroUchida/SandaBousaiNote#228]
P4ゆれがおさまったら、を作成したのでレビューをお願いします。

ほくせつ版のP4Yurega.jsを直接編集しています。
各チャートにつき画像を1枚だけピックアップして載せています。
ほくせつ版にはページ下部にクリックして内容が遷移するコンテンツがありましたが、よく確認したらページ上部の矢印のチャートと内容が完全に被っていたので、とりあえず省略して作ってみました。

**Comment by machimachida** [comment]
確認しました！
HeaderCardPart(上半分)とTitleCardPart(下半分)の二種類のヘッダーが共存してて、これは意図的なのかそうでないのかというところが気になったくらいかな
(Slackにも同じ内容を書きましたが念のため)
