### ISSUE TITLE
三田版のレビュー_P18家族で防災カイギ

### ISSUE THREAD

**Issue by kokyamad** [KentaroUchida/SandaBousaiNote#233]
自分で気になるところとしては

大地震が起こった時〜のカードが質素
水害等のtableが古代
GooglePlayのアイコンがガビガビ

**Comment by YamadaKouki12** [comment]
自分で気になるところとしては
- 大地震が起こった時〜のカードが質素
- 水害等のtableが古代
- GooglePlayのアイコンがガビガビ
