### ISSUE TITLE
PDFをダウンロードしても書いた内容が反映されていない

### ISSUE THREAD

**Issue by alttkymmm** [KentaroUchida/SandaBousaiNote#307]

**Comment by alttkymmm** [comment]
家族の連絡先と持ち物チェックボックスは少なくとも反応しなかったです。

**Comment by alttkymmm** [comment]
家族で防災カイギのチェックボックスは動いている...?

**Comment by machimachida** [comment]
PDFGeneratorの同期・非同期の問題だと思うので、適当なタイミングで更新します。

**Comment by machimachida** [comment]
最終日にForm周りの仕様変わったやつにPDF対応していなかったのと、非同期処理の問題でforEach -> forへの書き換えを急ぎでやってたときにfamilyList周りのfor-loopを一つ書き忘れてたのが原因でした。すみません。
